GEE_USERNAME: 'hafnersailing'

PIXEL_SPACING: 10
CRS: 'UTM'
ERROR_MARGIN: 0.01

SATELLITE_DATA:
  RECORDS:
    - SENSOR: 'sentinel2'
      PROCESSING_LEVEL: 'toa'
      BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B11', 'B12']
      PRODUCT: 'cloud_free_mosaic'
      DATE_RANGE: ['2018-06-01', '2018-09-01']
    - SENSOR: 'sentinel1'
      PROCESSING_LEVEL: 'grd'
      BANDS: ['VV', 'VH']
      PRODUCT: 'single_orbit_mosaic'
      DATE_RANGE: ['2018-06-01', '2018-09-01']

MICROSOFT_BUILDINGS:
  ID: 'buildings'
  PIXEL_PERCENTAGE: True
  ASSETS: []

ROI:
  ID: 'city_name'
  UTM_EPSG: ''
  LNG_RANGE: [0, 0]
  LAT_RANGE: [0, 0]

SAMPLING:
  PATCH_SIZE: 256
  SAMPLE_FRACTION: 0.3
  MAX_SAMPLE_SIZE: 800
  NEIGHBORHOOD_SIZE: 50
  SEED: 7
  PATH: 'C:/Users/shafner/urban_extraction/data/samples'

DOWNLOAD:
  TYPE: 'cloud' # drive or cloud
  BUCKET_NAME: 'urban_extraction_dataset_version4'
  DRIVE_FOLDER: 'gee_downloads_urban_extraction'
  TABLE_FORMAT: 'GeoJSON'
  IMAGE_FORMAT: 'GeoTIFF'