_BASE_: "base.yaml"

BUILDING_FOOTPRINTS:
  PIXEL_PERCENTAGE: True
  ASSETS: ['Bing/UnitedStates/Illinois', 'Bing/UnitedStates/Indiana']

ROI:
  ID: 'chicago'
  UTM_EPSG: 'EPSG:32616'
  LNG_RANGE: [-88.56222912494165, -86.83188244525415]
  LAT_RANGE: [41.30091434326551, 42.454260524602475]
