GEE_USERNAME: 'hafnersailing'
PIXEL_SPACING: 10
CRS: 'UTM'
ERROR_MARGIN: 0.01
ROIS_SUBSET: []

DOWNLOAD:
  TYPE: 'cloud' # drive or cloud
  BUCKET_NAME: 'sdg_dataset'
  DRIVE_FOLDER: 'gee_downloads_urban_extraction'
  TABLE_FORMAT: 'GeoJSON'
  IMAGE_FORMAT: 'GeoTIFF'

MICROSOFT_BUILDINGS:
  ID: 'buildings'
  PIXEL_PERCENTAGE: True
  ASSETS: []

SATELLITE_DATA:
  RECORDS:
    - SENSOR: 'sentinel2'
      PROCESSING_LEVEL: 'toa'
      BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B11', 'B12']
      PRODUCT: 'custom_composite'
      DATE_RANGE: ['2016-01-01', '2016-12-31']
    - SENSOR: 'sentinel1'
      PROCESSING_LEVEL: 'grd'
      BANDS: ['VV', 'VH']
      PRODUCT: 'single_orbit_mosaic'
      DATE_RANGE: ['2016-01-01', '2016-12-31']

ROIS:
  - ID: 'kigali'
    UTM_EPSG: 'EPSG:32736'
    LNG_RANGE: [29.95849300959009, 30.26885677912134]
    LAT_RANGE: [-2.101657307751142, -1.7901003960620236]
    LABELED: False
    BUILDING_ASSETS: []
  - ID: 'stockholm'
    UTM_EPSG: 'EPSG:32634'
    LNG_RANGE: [17.391164910411987, 18.577688347911987]
    LAT_RANGE: [59.06709644765132, 59.64386387354065]
    LABELED: False
    BUILDING_ASSETS: ['Stockholm/real_estate_data']
  - ID: 'beijing'
    UTM_EPSG: 'EPSG:32650'
    LNG_RANGE: [115.82870277658942, 117.38876137033942]
    LAT_RANGE: [39.57155310121824, 40.58031948558203]
    LABELED: False
    BUILDING_ASSETS: []
  - ID: 'cairo'
    UTM_EPSG: 'EPSG:32636'
    LNG_RANGE: [30.800354455240697, 31.684753869303197]
    LAT_RANGE: [29.872124498262135, 30.28922920339737]
    LABELED: False
    BUILDING_ASSETS: []
  - ID: 'dubai'
    UTM_EPSG: 'EPSG:32640'
    LNG_RANGE: [54.91984980201027, 55.687519479744644]
    LAT_RANGE: [24.802807169634416, 25.620344198413733]
    LABELED: False
    BUILDING_ASSETS: []
  - ID: 'riodejanairo'
    UTM_EPSG: 'EPSG:32723'
    LNG_RANGE: [-43.92522063608997, -42.80461516733997]
    LAT_RANGE: [-23.07030777852963, -22.44979689178131]
    LABELED: False
    BUILDING_ASSETS: []