_BASE_: "download_config.yaml"

ROIS_SUBSET: ['prague', 'amsterdam', 'riyadh', 'amman', 'damascus', 'nouakchott', 'zhengzhou', 'hefei', 'xian',
              'seoul', 'ibadan', 'benincity', 'abidjan', 'accra']

DOWNLOAD:
  TYPE: 'drive' # drive or cloud
  BUCKET_NAME: 'urban_dataset'
  DRIVE_FOLDER: 'ghsl2018'