_BASE_: "base.yaml"

BUILDING_FOOTPRINTS:
  PIXEL_PERCENTAGE: True
  ASSETS: ['Bing/UnitedStates/NewYork', 'Bing/UnitedStates/NewJersey', 'Bing/UnitedStates/Connecticut']

ROI:
  ID: 'newyork'
  UTM_EPSG: 'EPSG:32618'
  LNG_RANGE: [-74.47337660334584, -72.88035902522084]
  LAT_RANGE: [40.47063024415202, 41.15039435583894]
