_BASE_: "download_config.yaml"

ROIS_SUBSET: ['albuquerque', 'atlanta', 'calgary', 'charlston', 'chicago', 'columbus', 'dallas', 'daressalam',
              'denver', 'elpaso', 'houston', 'kampala', 'kansascity', 'losangeles', 'miami', 'minneapolis', 'montreal',
              'mwanza', 'newyork', 'phoenix', 'quebec', 'saltlakecity', 'sandiego', 'sanfrancisco', 'santafe', 'seattle',
              'stgeorge', 'toronto', 'tucson', 'vancouver', 'winnipeg']