_BASE_: "download_config.yaml"

ROIS_SUBSET: ['albuquerque', 'atlanta', 'calgary', 'charlston', 'columbus', 'dallas', 'denver', 'elpaso', 'houston',
              'kansascity', 'lasvegas', 'losangeles', 'miami', 'minneapolis', 'montreal', 'newyork', 'phoenix',
              'quebec', 'saltlakecity', 'sandiego', 'sanfrancisco', 'santafe', 'seattle', 'stgeorge', 'toronto',
              'tucson', 'vancouver', 'winnipeg']