GEE_USERNAME: 'hafnersailing'
PIXEL_SPACING: 10
CRS: 'UTM'
ERROR_MARGIN: 0.01

AOI_SUBSET: [
  'paris',
  'pisa',
  'rennes',
  'saclay_e',
  'bordeaux',
  'bercy',
  'hongkong',
  'aguasclaras',
  'abudhabi',
]

DOWNLOAD:
  TYPE: 'cloud' # drive or cloud
  BUCKET_NAME: 'oscd_multitemporal_dataset'
  DRIVE_FOLDER: 'oscd_multitemporal_dataset'
  TABLE_FORMAT: 'GeoJSON'
  IMAGE_FORMAT: 'GeoTIFF'


SATELLITE_DATA:
  RECORDS:
    - SENSOR: 'sentinel2'
      PROCESSING_LEVEL: 'toa'
      BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B11', 'B12']
      PRODUCT: 'custom_composite'
    - SENSOR: 'sentinel1'
      PROCESSING_LEVEL: 'grd'
      BANDS: ['VV', 'VH']
      PRODUCT: 'single_orbit_mosaic'
